# Generated by Django 4.2.7 on 2023-12-12 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimousDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('meta_cookies', models.CharField(max_length=256)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='No data about image', verbose_name='Malumot')),
                ('image', models.FileField(null=True, upload_to='images/arts/', verbose_name='Surat')),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('search_time', models.PositiveBigIntegerField(default=0, editable=False)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('on_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-likes',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_key', models.CharField(editable=False, max_length=14)),
                ('fullname', models.CharField(max_length=256, verbose_name="To'liq ismi")),
                ('about', models.TextField(verbose_name='Malumot')),
                ('image', models.ImageField(upload_to='images/artist/', verbose_name='Surati')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_obj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('ordering', models.PositiveBigIntegerField(default=0)),
                ('has_image', models.BooleanField(default=False)),
                ('dark_image', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
                ('light_image', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
                ('wall_image', models.ImageField(blank=True, null=True, upload_to='images/three/wall/room/')),
                ('floor_image', models.ImageField(blank=True, null=True, upload_to='images/three/floor/room/')),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images')),
                ('data', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('object_elem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='main.art')),
            ],
        ),
        migrations.CreateModel(
            name='OnVerifyArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='No data about image', null=True, verbose_name='Malumot')),
                ('image', models.CharField(blank=True, max_length=99999, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nomi')),
                ('text', models.TextField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('rates', models.PositiveBigIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verify_arts', to='main.artist', verbose_name='Sanatkor')),
                ('categories', models.ManyToManyField(blank=True, related_name='verify_carts', to='main.category', verbose_name='Turi')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.art')),
                ('web_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.webuser')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arts', to='main.artist', verbose_name='Sanatkor'),
        ),
        migrations.AddField(
            model_name='art',
            name='categories',
            field=models.ManyToManyField(related_name='carts', to='main.category', verbose_name='Turi'),
        ),
    ]
